function normCountry(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const NATIONAL_FLAG: Record<string, string> = {
  france: "🇫🇷",
  germany: "🇩🇪",
  allemagne: "🇩🇪",
  italy: "🇮🇹",
  italie: "🇮🇹",
  spain: "🇪🇸",
  espagne: "🇪🇸",
  portugal: "🇵🇹",
  belgium: "🇧🇪",
  belgique: "🇧🇪",
  netherlands: "🇳🇱",
  "pays bas": "🇳🇱",
  holland: "🇳🇱",
  denmark: "🇩🇰",
  danemark: "🇩🇰",
  sweden: "🇸🇪",
  suede: "🇸🇪",
  norway: "🇳🇴",
  norvege: "🇳🇴",
  finland: "🇫🇮",
  finlande: "🇫🇮",
  "faroe islands": "🇫🇴",
  "iles feroe": "🇫🇴",
  iceland: "🇮🇸",
  islande: "🇮🇸",
  ireland: "🇮🇪",
  irlande: "🇮🇪",
  england: "🇬🇧",
  angleterre: "🇬🇧",
  scotland: "🇬🇧",
  ecosse: "🇬🇧",
  wales: "🇬🇧",
  galles: "🇬🇧",
  "northern ireland": "🇬🇧",
  poland: "🇵🇱",
  pologne: "🇵🇱",
  czechia: "🇨🇿",
  "czech republic": "🇨🇿",
  "republique tcheque": "🇨🇿",
  slovakia: "🇸🇰",
  slovaquie: "🇸🇰",
  slovenia: "🇸🇮",
  slovenie: "🇸🇮",
  croatia: "🇭🇷",
  croatie: "🇭🇷",
  serbia: "🇷🇸",
  serbie: "🇷🇸",
  "bosnia and herzegovina": "🇧🇦",
  "bosnie herzegovine": "🇧🇦",
  montenegro: "🇲🇪",
  albania: "🇦🇱",
  albanie: "🇦🇱",
  "north macedonia": "🇲🇰",
  "macedoine du nord": "🇲🇰",
  kosovo: "🇽🇰",
  greece: "🇬🇷",
  grece: "🇬🇷",
  turkey: "🇹🇷",
  turquie: "🇹🇷",
  romania: "🇷🇴",
  roumanie: "🇷🇴",
  bulgaria: "🇧🇬",
  bulgarie: "🇧🇬",
  hungary: "🇭🇺",
  hongrie: "🇭🇺",
  austria: "🇦🇹",
  autriche: "🇦🇹",
  switzerland: "🇨🇭",
  suisse: "🇨🇭",
  ukraine: "🇺🇦",
  georgia: "🇬🇪",
  georgie: "🇬🇪",
  armenia: "🇦🇲",
  armenie: "🇦🇲",
  azerbaijan: "🇦🇿",
  azerbaidjan: "🇦🇿",
  kazakhstan: "🇰🇿",
  moldova: "🇲🇩",
  moldavie: "🇲🇩",
  belarus: "🇧🇾",
  bielorussie: "🇧🇾",
  estonia: "🇪🇪",
  estonie: "🇪🇪",
  latvia: "🇱🇻",
  lettonie: "🇱🇻",
  lithuania: "🇱🇹",
  lituanie: "🇱🇹",
  luxembourg: "🇱🇺",
  malta: "🇲🇹",
  malte: "🇲🇹",
  cyprus: "🇨🇾",
  chypre: "🇨🇾",
  liechtenstein: "🇱🇮",
  "san marino": "🇸🇲",
  andorra: "🇦🇩",
  gibraltar: "🇬🇮",
  israel: "🇮🇱",
  morocco: "🇲🇦",
  maroc: "🇲🇦",
  algeria: "🇩🇿",
  algerie: "🇩🇿",
  tunisia: "🇹🇳",
  tunisie: "🇹🇳",
  egypt: "🇪🇬",
  egypte: "🇪🇬",
  senegal: "🇸🇳",
  guinea: "🇬🇳",
  guinee: "🇬🇳",
  kenya: "🇰🇪",
  ghana: "🇬🇭",
  nigeria: "🇳🇬",
  cameroon: "🇨🇲",
  cameroun: "🇨🇲",
  "ivory coast": "🇨🇮",
  "cote d ivoire": "🇨🇮",
  mali: "🇲🇱",
  "south africa": "🇿🇦",
  "afrique du sud": "🇿🇦",
  japan: "🇯🇵",
  japon: "🇯🇵",
  "south korea": "🇰🇷",
  "coree du sud": "🇰🇷",
  china: "🇨🇳",
  chine: "🇨🇳",
  australia: "🇦🇺",
  australie: "🇦🇺",
  "new zealand": "🇳🇿",
  "nouvelle zelande": "🇳🇿",
  usa: "🇺🇸",
  "united states": "🇺🇸",
  "etats unis": "🇺🇸",
  canada: "🇨🇦",
  mexico: "🇲🇽",
  mexique: "🇲🇽",
  brazil: "🇧🇷",
  bresil: "🇧🇷",
  argentina: "🇦🇷",
  argentine: "🇦🇷",
  uruguay: "🇺🇾",
  colombia: "🇨🇴",
  colombie: "🇨🇴",
  chile: "🇨🇱",
  chili: "🇨🇱",
  peru: "🇵🇪",
  perou: "🇵🇪",
  ecuador: "🇪🇨",
  equateur: "🇪🇨",
  paraguay: "🇵🇾",
  venezuela: "🇻🇪",
};

export function nationalTeamFlag(name: string): string | null {
  return NATIONAL_FLAG[normCountry(name)] ?? null;
}

export function nationalTeamCountryCode(name: string): string | null {
  const flag = nationalTeamFlag(name);
  if (!flag) return null;
  const regional = [...flag];
  if (regional.length !== 2) return null;
  const letters = regional.map((char) => {
    const point = char.codePointAt(0);
    if (point === undefined || point < 0x1f1e6 || point > 0x1f1ff) return "";
    return String.fromCharCode(point - 0x1f1e6 + 65);
  }).join("");
  return /^[A-Z]{2}$/.test(letters) ? letters : null;
}
