/* AUTO-GENERATED by ASTRA SEMANTIC FLOW AUTO-REPAIR Ω. DO NOT EDIT BY HAND. */
export type SemanticAutoLink = {
  source: string;
  href: string;
  anchor: string;
  relation: "child" | "contextual";
  reason: string;
};

export const SEMANTIC_AUTO_LINKS: SemanticAutoLink[] = [];
