/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActuRouteImport } from './routes/actu'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BundesligaRouteImport } from './routes/bundesliga'
import { Route as CalculateurMiseRouteImport } from './routes/calculateur-mise'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ChampionshipRouteImport } from './routes/championship'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as ComparerCotesRouteImport } from './routes/comparer-cotes'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as GeoHealthRouteImport } from './routes/geo-health'
import { Route as GoRouteImport } from './routes/go'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as JeuResponsableRouteImport } from './routes/jeu-responsable'
import { Route as LaLigaRouteImport } from './routes/la-liga'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as Ligue1RouteImport } from './routes/ligue-1'
import { Route as LigueDesChampionsRouteImport } from './routes/ligue-des-champions'
import { Route as LigueEuropaRouteImport } from './routes/ligue-europa'
import { Route as MeilleurSitePronosticRouteImport } from './routes/meilleur-site-pronostic'
import { Route as MeilleuresCotesRouteImport } from './routes/meilleures-cotes'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as PariDuJourRouteImport } from './routes/pari-du-jour'
import { Route as PariEnDirectRouteImport } from './routes/pari-en-direct'
import { Route as ParisFootballRouteImport } from './routes/paris-football'
import { Route as PolitiquePubliciteRouteImport } from './routes/politique-publicite'
import { Route as PortefeuilleMotsClesRouteImport } from './routes/portefeuille-mots-cles'
import { Route as PredictionHistoryRouteImport } from './routes/prediction-history'
import { Route as PremierLeagueRouteImport } from './routes/premier-league'
import { Route as PressRouteImport } from './routes/press'
import { Route as PronosFootballRouteImport } from './routes/pronos-football'
import { Route as PronosticsFootballRouteImport } from './routes/pronostics-football'
import { Route as PronosticsSportifsRouteImport } from './routes/pronostics-sportifs'
import { Route as RedactionRouteImport } from './routes/redaction'
import { Route as ResultatsFootballRouteImport } from './routes/resultats-football'
import { Route as ScoreDataMethodologyRouteImport } from './routes/score-data-methodology'
import { Route as ScoreHunterRouteImport } from './routes/score-hunter'
import { Route as ScoresEnDirectRouteImport } from './routes/scores-en-direct'
import { Route as SerieARouteImport } from './routes/serie-a'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ActuIndexRouteImport } from './routes/actu.index'
import { Route as ActuDayRouteImport } from './routes/actu.$day'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as AdminEditorialRouteImport } from './routes/admin_.editorial'
import { Route as AdminSocialRouteImport } from './routes/admin_.social'
import { Route as AuteursBetgptEditorialRouteImport } from './routes/auteurs_.betgpt-editorial'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CalendrierIndexRouteImport } from './routes/calendrier.index'
import { Route as CalendrierSlugRouteImport } from './routes/calendrier.$slug'
import { Route as ClassementIndexRouteImport } from './routes/classement.index'
import { Route as ClassementSlugRouteImport } from './routes/classement.$slug'
import { Route as CotesMatchIdRouteImport } from './routes/cotes.$matchId'
import { Route as EquipeTeamRouteImport } from './routes/equipe.$team'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumThreadIdRouteImport } from './routes/forum.$threadId'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as OutilsIndexRouteImport } from './routes/outils.index'
import { Route as OutilsSlugRouteImport } from './routes/outils.$slug'
import { Route as PredictionPredictionIdRouteImport } from './routes/prediction.$predictionId'
import { Route as PronoMatchIdRouteImport } from './routes/prono.$matchId'
import { Route as PronosticsFootballIndexRouteImport } from './routes/pronostics-football.index'
import { Route as PronosticsFootballLeagueRouteImport } from './routes/pronostics-football.$league'
import { Route as PronosticsFootballAujourdhuiRouteImport } from './routes/pronostics-football.aujourdhui'
import { Route as PronosticsFootballDemainRouteImport } from './routes/pronostics-football.demain'
import { Route as RapportsPrecisionRouteImport } from './routes/rapports.precision'
import { Route as ResultatMatchIdRouteImport } from './routes/resultat.$matchId'
import { Route as ResultatsFootballIndexRouteImport } from './routes/resultats-football.index'
import { Route as ResultatsFootballLeagueRouteImport } from './routes/resultats-football.$league'
import { Route as ResultatsFootballAujourdhuiRouteImport } from './routes/resultats-football.aujourdhui'
import { Route as ResultatsFootballHierRouteImport } from './routes/resultats-football.hier'
import { Route as ScoreHunterIndexRouteImport } from './routes/score-hunter.index'
import { Route as ScoreHunterScenarioRouteImport } from './routes/score-hunter.$scenario'
import { Route as ScoreMatchIdRouteImport } from './routes/score.$matchId'
import { Route as ScoresEnDirectIndexRouteImport } from './routes/scores-en-direct.index'
import { Route as ScoresEnDirectLeagueRouteImport } from './routes/scores-en-direct.$league'
import { Route as StatisticsIndexRouteImport } from './routes/statistics.index'
import { Route as StatisticsMostCommonScoresRouteImport } from './routes/statistics.most-common-scores'
import { Route as StatisticsLeagueMostCommonScoresRouteImport } from './routes/statistics.$league.most-common-scores'
import { Route as StatisticsLeaguesHighest00RouteImport } from './routes/statistics.leagues.highest-0-0'
import { Route as StatisticsLeaguesLowest00RouteImport } from './routes/statistics.leagues.lowest-0-0'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActuRoute = ActuRouteImport.update({
  id: '/actu',
  path: '/actu',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BundesligaRoute = BundesligaRouteImport.update({
  id: '/bundesliga',
  path: '/bundesliga',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateurMiseRoute = CalculateurMiseRouteImport.update({
  id: '/calculateur-mise',
  path: '/calculateur-mise',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipRoute = ChampionshipRouteImport.update({
  id: '/championship',
  path: '/championship',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerCotesRoute = ComparerCotesRouteImport.update({
  id: '/comparer-cotes',
  path: '/comparer-cotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoHealthRoute = GeoHealthRouteImport.update({
  id: '/geo-health',
  path: '/geo-health',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuResponsableRoute = JeuResponsableRouteImport.update({
  id: '/jeu-responsable',
  path: '/jeu-responsable',
  getParentRoute: () => rootRouteImport,
} as any)
const LaLigaRoute = LaLigaRouteImport.update({
  id: '/la-liga',
  path: '/la-liga',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const Ligue1Route = Ligue1RouteImport.update({
  id: '/ligue-1',
  path: '/ligue-1',
  getParentRoute: () => rootRouteImport,
} as any)
const LigueDesChampionsRoute = LigueDesChampionsRouteImport.update({
  id: '/ligue-des-champions',
  path: '/ligue-des-champions',
  getParentRoute: () => rootRouteImport,
} as any)
const LigueEuropaRoute = LigueEuropaRouteImport.update({
  id: '/ligue-europa',
  path: '/ligue-europa',
  getParentRoute: () => rootRouteImport,
} as any)
const MeilleurSitePronosticRoute = MeilleurSitePronosticRouteImport.update({
  id: '/meilleur-site-pronostic',
  path: '/meilleur-site-pronostic',
  getParentRoute: () => rootRouteImport,
} as any)
const MeilleuresCotesRoute = MeilleuresCotesRouteImport.update({
  id: '/meilleures-cotes',
  path: '/meilleures-cotes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const PariDuJourRoute = PariDuJourRouteImport.update({
  id: '/pari-du-jour',
  path: '/pari-du-jour',
  getParentRoute: () => rootRouteImport,
} as any)
const PariEnDirectRoute = PariEnDirectRouteImport.update({
  id: '/pari-en-direct',
  path: '/pari-en-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ParisFootballRoute = ParisFootballRouteImport.update({
  id: '/paris-football',
  path: '/paris-football',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiquePubliciteRoute = PolitiquePubliciteRouteImport.update({
  id: '/politique-publicite',
  path: '/politique-publicite',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefeuilleMotsClesRoute = PortefeuilleMotsClesRouteImport.update({
  id: '/portefeuille-mots-cles',
  path: '/portefeuille-mots-cles',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionHistoryRoute = PredictionHistoryRouteImport.update({
  id: '/prediction-history',
  path: '/prediction-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PremierLeagueRoute = PremierLeagueRouteImport.update({
  id: '/premier-league',
  path: '/premier-league',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PronosFootballRoute = PronosFootballRouteImport.update({
  id: '/pronos-football',
  path: '/pronos-football',
  getParentRoute: () => rootRouteImport,
} as any)
const PronosticsFootballRoute = PronosticsFootballRouteImport.update({
  id: '/pronostics-football',
  path: '/pronostics-football',
  getParentRoute: () => rootRouteImport,
} as any)
const PronosticsSportifsRoute = PronosticsSportifsRouteImport.update({
  id: '/pronostics-sportifs',
  path: '/pronostics-sportifs',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactionRoute = RedactionRouteImport.update({
  id: '/redaction',
  path: '/redaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsFootballRoute = ResultatsFootballRouteImport.update({
  id: '/resultats-football',
  path: '/resultats-football',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreDataMethodologyRoute = ScoreDataMethodologyRouteImport.update({
  id: '/score-data-methodology',
  path: '/score-data-methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreHunterRoute = ScoreHunterRouteImport.update({
  id: '/score-hunter',
  path: '/score-hunter',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresEnDirectRoute = ScoresEnDirectRouteImport.update({
  id: '/scores-en-direct',
  path: '/scores-en-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieARoute = SerieARouteImport.update({
  id: '/serie-a',
  path: '/serie-a',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActuIndexRoute = ActuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActuRoute,
} as any)
const ActuDayRoute = ActuDayRouteImport.update({
  id: '/$day',
  path: '/$day',
  getParentRoute: () => ActuRoute,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActualitesRoute,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActualitesRoute,
} as any)
const AdminEditorialRoute = AdminEditorialRouteImport.update({
  id: '/admin_/editorial',
  path: '/admin/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/admin_/social',
  path: '/admin/social',
  getParentRoute: () => rootRouteImport,
} as any)
const AuteursBetgptEditorialRoute = AuteursBetgptEditorialRouteImport.update({
  id: '/auteurs_/betgpt-editorial',
  path: '/auteurs/betgpt-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CalendrierIndexRoute = CalendrierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalendrierRoute,
} as any)
const CalendrierSlugRoute = CalendrierSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CalendrierRoute,
} as any)
const ClassementIndexRoute = ClassementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassementRoute,
} as any)
const ClassementSlugRoute = ClassementSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClassementRoute,
} as any)
const CotesMatchIdRoute = CotesMatchIdRouteImport.update({
  id: '/cotes/$matchId',
  path: '/cotes/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeTeamRoute = EquipeTeamRouteImport.update({
  id: '/equipe/$team',
  path: '/equipe/$team',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumRoute,
} as any)
const ForumThreadIdRoute = ForumThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ForumRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsIndexRoute = OutilsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutilsRoute,
} as any)
const OutilsSlugRoute = OutilsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OutilsRoute,
} as any)
const PredictionPredictionIdRoute = PredictionPredictionIdRouteImport.update({
  id: '/prediction/$predictionId',
  path: '/prediction/$predictionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PronoMatchIdRoute = PronoMatchIdRouteImport.update({
  id: '/prono/$matchId',
  path: '/prono/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PronosticsFootballIndexRoute = PronosticsFootballIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PronosticsFootballRoute,
} as any)
const PronosticsFootballLeagueRoute =
  PronosticsFootballLeagueRouteImport.update({
    id: '/$league',
    path: '/$league',
    getParentRoute: () => PronosticsFootballRoute,
  } as any)
const PronosticsFootballAujourdhuiRoute =
  PronosticsFootballAujourdhuiRouteImport.update({
    id: '/aujourdhui',
    path: '/aujourdhui',
    getParentRoute: () => PronosticsFootballRoute,
  } as any)
const PronosticsFootballDemainRoute =
  PronosticsFootballDemainRouteImport.update({
    id: '/demain',
    path: '/demain',
    getParentRoute: () => PronosticsFootballRoute,
  } as any)
const RapportsPrecisionRoute = RapportsPrecisionRouteImport.update({
  id: '/rapports/precision',
  path: '/rapports/precision',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatMatchIdRoute = ResultatMatchIdRouteImport.update({
  id: '/resultat/$matchId',
  path: '/resultat/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsFootballIndexRoute = ResultatsFootballIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultatsFootballRoute,
} as any)
const ResultatsFootballLeagueRoute = ResultatsFootballLeagueRouteImport.update({
  id: '/$league',
  path: '/$league',
  getParentRoute: () => ResultatsFootballRoute,
} as any)
const ResultatsFootballAujourdhuiRoute =
  ResultatsFootballAujourdhuiRouteImport.update({
    id: '/aujourdhui',
    path: '/aujourdhui',
    getParentRoute: () => ResultatsFootballRoute,
  } as any)
const ResultatsFootballHierRoute = ResultatsFootballHierRouteImport.update({
  id: '/hier',
  path: '/hier',
  getParentRoute: () => ResultatsFootballRoute,
} as any)
const ScoreHunterIndexRoute = ScoreHunterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoreHunterRoute,
} as any)
const ScoreHunterScenarioRoute = ScoreHunterScenarioRouteImport.update({
  id: '/$scenario',
  path: '/$scenario',
  getParentRoute: () => ScoreHunterRoute,
} as any)
const ScoreMatchIdRoute = ScoreMatchIdRouteImport.update({
  id: '/score/$matchId',
  path: '/score/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresEnDirectIndexRoute = ScoresEnDirectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoresEnDirectRoute,
} as any)
const ScoresEnDirectLeagueRoute = ScoresEnDirectLeagueRouteImport.update({
  id: '/$league',
  path: '/$league',
  getParentRoute: () => ScoresEnDirectRoute,
} as any)
const StatisticsIndexRoute = StatisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatisticsRoute,
} as any)
const StatisticsMostCommonScoresRoute =
  StatisticsMostCommonScoresRouteImport.update({
    id: '/most-common-scores',
    path: '/most-common-scores',
    getParentRoute: () => StatisticsRoute,
  } as any)
const StatisticsLeagueMostCommonScoresRoute =
  StatisticsLeagueMostCommonScoresRouteImport.update({
    id: '/$league/most-common-scores',
    path: '/$league/most-common-scores',
    getParentRoute: () => StatisticsRoute,
  } as any)
const StatisticsLeaguesHighest00Route =
  StatisticsLeaguesHighest00RouteImport.update({
    id: '/leagues/highest-0-0',
    path: '/leagues/highest-0-0',
    getParentRoute: () => StatisticsRoute,
  } as any)
const StatisticsLeaguesLowest00Route =
  StatisticsLeaguesLowest00RouteImport.update({
    id: '/leagues/lowest-0-0',
    path: '/leagues/lowest-0-0',
    getParentRoute: () => StatisticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/about': typeof AboutRoute
  '/actu': typeof ActuRouteWithChildren
  '/actualites': typeof ActualitesRouteWithChildren
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/bundesliga': typeof BundesligaRoute
  '/calculateur-mise': typeof CalculateurMiseRoute
  '/calendrier': typeof CalendrierRouteWithChildren
  '/cgu': typeof CguRoute
  '/championship': typeof ChampionshipRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/classement': typeof ClassementRouteWithChildren
  '/comparer-cotes': typeof ComparerCotesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-sources': typeof DataSourcesRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/forum': typeof ForumRouteWithChildren
  '/geo-health': typeof GeoHealthRoute
  '/go': typeof GoRoute
  '/guides': typeof GuidesRouteWithChildren
  '/jeu-responsable': typeof JeuResponsableRoute
  '/la-liga': typeof LaLigaRoute
  '/lab': typeof LabRoute
  '/ledger': typeof LedgerRoute
  '/ligue-1': typeof Ligue1Route
  '/ligue-des-champions': typeof LigueDesChampionsRoute
  '/ligue-europa': typeof LigueEuropaRoute
  '/meilleur-site-pronostic': typeof MeilleurSitePronosticRoute
  '/meilleures-cotes': typeof MeilleuresCotesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methodology': typeof MethodologyRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outils': typeof OutilsRouteWithChildren
  '/pari-du-jour': typeof PariDuJourRoute
  '/pari-en-direct': typeof PariEnDirectRoute
  '/paris-football': typeof ParisFootballRoute
  '/politique-publicite': typeof PolitiquePubliciteRoute
  '/portefeuille-mots-cles': typeof PortefeuilleMotsClesRoute
  '/prediction-history': typeof PredictionHistoryRoute
  '/premier-league': typeof PremierLeagueRoute
  '/press': typeof PressRoute
  '/pronos-football': typeof PronosFootballRoute
  '/pronostics-football': typeof PronosticsFootballRouteWithChildren
  '/pronostics-sportifs': typeof PronosticsSportifsRoute
  '/redaction': typeof RedactionRoute
  '/resultats-football': typeof ResultatsFootballRouteWithChildren
  '/score-data-methodology': typeof ScoreDataMethodologyRoute
  '/score-hunter': typeof ScoreHunterRouteWithChildren
  '/scores-en-direct': typeof ScoresEnDirectRouteWithChildren
  '/serie-a': typeof SerieARoute
  '/sitemap': typeof SitemapRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/actu/$day': typeof ActuDayRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/social': typeof AdminSocialRoute
  '/auteurs/betgpt-editorial': typeof AuteursBetgptEditorialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calendrier/$slug': typeof CalendrierSlugRoute
  '/classement/$slug': typeof ClassementSlugRoute
  '/cotes/$matchId': typeof CotesMatchIdRoute
  '/equipe/$team': typeof EquipeTeamRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/prediction/$predictionId': typeof PredictionPredictionIdRoute
  '/prono/$matchId': typeof PronoMatchIdRoute
  '/pronostics-football/$league': typeof PronosticsFootballLeagueRoute
  '/pronostics-football/aujourdhui': typeof PronosticsFootballAujourdhuiRoute
  '/pronostics-football/demain': typeof PronosticsFootballDemainRoute
  '/rapports/precision': typeof RapportsPrecisionRoute
  '/resultat/$matchId': typeof ResultatMatchIdRoute
  '/resultats-football/$league': typeof ResultatsFootballLeagueRoute
  '/resultats-football/aujourdhui': typeof ResultatsFootballAujourdhuiRoute
  '/resultats-football/hier': typeof ResultatsFootballHierRoute
  '/score-hunter/$scenario': typeof ScoreHunterScenarioRoute
  '/score/$matchId': typeof ScoreMatchIdRoute
  '/scores-en-direct/$league': typeof ScoresEnDirectLeagueRoute
  '/statistics/most-common-scores': typeof StatisticsMostCommonScoresRoute
  '/actu/': typeof ActuIndexRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/calendrier/': typeof CalendrierIndexRoute
  '/classement/': typeof ClassementIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/pronostics-football/': typeof PronosticsFootballIndexRoute
  '/resultats-football/': typeof ResultatsFootballIndexRoute
  '/score-hunter/': typeof ScoreHunterIndexRoute
  '/scores-en-direct/': typeof ScoresEnDirectIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/statistics/$league/most-common-scores': typeof StatisticsLeagueMostCommonScoresRoute
  '/statistics/leagues/highest-0-0': typeof StatisticsLeaguesHighest00Route
  '/statistics/leagues/lowest-0-0': typeof StatisticsLeaguesLowest00Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bundesliga': typeof BundesligaRoute
  '/calculateur-mise': typeof CalculateurMiseRoute
  '/cgu': typeof CguRoute
  '/championship': typeof ChampionshipRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/comparer-cotes': typeof ComparerCotesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-sources': typeof DataSourcesRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/geo-health': typeof GeoHealthRoute
  '/go': typeof GoRoute
  '/jeu-responsable': typeof JeuResponsableRoute
  '/la-liga': typeof LaLigaRoute
  '/lab': typeof LabRoute
  '/ledger': typeof LedgerRoute
  '/ligue-1': typeof Ligue1Route
  '/ligue-des-champions': typeof LigueDesChampionsRoute
  '/ligue-europa': typeof LigueEuropaRoute
  '/meilleur-site-pronostic': typeof MeilleurSitePronosticRoute
  '/meilleures-cotes': typeof MeilleuresCotesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methodology': typeof MethodologyRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pari-du-jour': typeof PariDuJourRoute
  '/pari-en-direct': typeof PariEnDirectRoute
  '/paris-football': typeof ParisFootballRoute
  '/politique-publicite': typeof PolitiquePubliciteRoute
  '/portefeuille-mots-cles': typeof PortefeuilleMotsClesRoute
  '/prediction-history': typeof PredictionHistoryRoute
  '/premier-league': typeof PremierLeagueRoute
  '/press': typeof PressRoute
  '/pronos-football': typeof PronosFootballRoute
  '/pronostics-sportifs': typeof PronosticsSportifsRoute
  '/redaction': typeof RedactionRoute
  '/score-data-methodology': typeof ScoreDataMethodologyRoute
  '/serie-a': typeof SerieARoute
  '/sitemap': typeof SitemapRoute
  '/actu/$day': typeof ActuDayRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/social': typeof AdminSocialRoute
  '/auteurs/betgpt-editorial': typeof AuteursBetgptEditorialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calendrier/$slug': typeof CalendrierSlugRoute
  '/classement/$slug': typeof ClassementSlugRoute
  '/cotes/$matchId': typeof CotesMatchIdRoute
  '/equipe/$team': typeof EquipeTeamRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/prediction/$predictionId': typeof PredictionPredictionIdRoute
  '/prono/$matchId': typeof PronoMatchIdRoute
  '/pronostics-football/$league': typeof PronosticsFootballLeagueRoute
  '/pronostics-football/aujourdhui': typeof PronosticsFootballAujourdhuiRoute
  '/pronostics-football/demain': typeof PronosticsFootballDemainRoute
  '/rapports/precision': typeof RapportsPrecisionRoute
  '/resultat/$matchId': typeof ResultatMatchIdRoute
  '/resultats-football/$league': typeof ResultatsFootballLeagueRoute
  '/resultats-football/aujourdhui': typeof ResultatsFootballAujourdhuiRoute
  '/resultats-football/hier': typeof ResultatsFootballHierRoute
  '/score-hunter/$scenario': typeof ScoreHunterScenarioRoute
  '/score/$matchId': typeof ScoreMatchIdRoute
  '/scores-en-direct/$league': typeof ScoresEnDirectLeagueRoute
  '/statistics/most-common-scores': typeof StatisticsMostCommonScoresRoute
  '/actu': typeof ActuIndexRoute
  '/actualites': typeof ActualitesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/calendrier': typeof CalendrierIndexRoute
  '/classement': typeof ClassementIndexRoute
  '/forum': typeof ForumIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/outils': typeof OutilsIndexRoute
  '/pronostics-football': typeof PronosticsFootballIndexRoute
  '/resultats-football': typeof ResultatsFootballIndexRoute
  '/score-hunter': typeof ScoreHunterIndexRoute
  '/scores-en-direct': typeof ScoresEnDirectIndexRoute
  '/statistics': typeof StatisticsIndexRoute
  '/statistics/$league/most-common-scores': typeof StatisticsLeagueMostCommonScoresRoute
  '/statistics/leagues/highest-0-0': typeof StatisticsLeaguesHighest00Route
  '/statistics/leagues/lowest-0-0': typeof StatisticsLeaguesLowest00Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/about': typeof AboutRoute
  '/actu': typeof ActuRouteWithChildren
  '/actualites': typeof ActualitesRouteWithChildren
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/bundesliga': typeof BundesligaRoute
  '/calculateur-mise': typeof CalculateurMiseRoute
  '/calendrier': typeof CalendrierRouteWithChildren
  '/cgu': typeof CguRoute
  '/championship': typeof ChampionshipRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/classement': typeof ClassementRouteWithChildren
  '/comparer-cotes': typeof ComparerCotesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-sources': typeof DataSourcesRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/forum': typeof ForumRouteWithChildren
  '/geo-health': typeof GeoHealthRoute
  '/go': typeof GoRoute
  '/guides': typeof GuidesRouteWithChildren
  '/jeu-responsable': typeof JeuResponsableRoute
  '/la-liga': typeof LaLigaRoute
  '/lab': typeof LabRoute
  '/ledger': typeof LedgerRoute
  '/ligue-1': typeof Ligue1Route
  '/ligue-des-champions': typeof LigueDesChampionsRoute
  '/ligue-europa': typeof LigueEuropaRoute
  '/meilleur-site-pronostic': typeof MeilleurSitePronosticRoute
  '/meilleures-cotes': typeof MeilleuresCotesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methodology': typeof MethodologyRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outils': typeof OutilsRouteWithChildren
  '/pari-du-jour': typeof PariDuJourRoute
  '/pari-en-direct': typeof PariEnDirectRoute
  '/paris-football': typeof ParisFootballRoute
  '/politique-publicite': typeof PolitiquePubliciteRoute
  '/portefeuille-mots-cles': typeof PortefeuilleMotsClesRoute
  '/prediction-history': typeof PredictionHistoryRoute
  '/premier-league': typeof PremierLeagueRoute
  '/press': typeof PressRoute
  '/pronos-football': typeof PronosFootballRoute
  '/pronostics-football': typeof PronosticsFootballRouteWithChildren
  '/pronostics-sportifs': typeof PronosticsSportifsRoute
  '/redaction': typeof RedactionRoute
  '/resultats-football': typeof ResultatsFootballRouteWithChildren
  '/score-data-methodology': typeof ScoreDataMethodologyRoute
  '/score-hunter': typeof ScoreHunterRouteWithChildren
  '/scores-en-direct': typeof ScoresEnDirectRouteWithChildren
  '/serie-a': typeof SerieARoute
  '/sitemap': typeof SitemapRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/actu/$day': typeof ActuDayRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin_/editorial': typeof AdminEditorialRoute
  '/admin_/social': typeof AdminSocialRoute
  '/auteurs_/betgpt-editorial': typeof AuteursBetgptEditorialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calendrier/$slug': typeof CalendrierSlugRoute
  '/classement/$slug': typeof ClassementSlugRoute
  '/cotes/$matchId': typeof CotesMatchIdRoute
  '/equipe/$team': typeof EquipeTeamRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/prediction/$predictionId': typeof PredictionPredictionIdRoute
  '/prono/$matchId': typeof PronoMatchIdRoute
  '/pronostics-football/$league': typeof PronosticsFootballLeagueRoute
  '/pronostics-football/aujourdhui': typeof PronosticsFootballAujourdhuiRoute
  '/pronostics-football/demain': typeof PronosticsFootballDemainRoute
  '/rapports/precision': typeof RapportsPrecisionRoute
  '/resultat/$matchId': typeof ResultatMatchIdRoute
  '/resultats-football/$league': typeof ResultatsFootballLeagueRoute
  '/resultats-football/aujourdhui': typeof ResultatsFootballAujourdhuiRoute
  '/resultats-football/hier': typeof ResultatsFootballHierRoute
  '/score-hunter/$scenario': typeof ScoreHunterScenarioRoute
  '/score/$matchId': typeof ScoreMatchIdRoute
  '/scores-en-direct/$league': typeof ScoresEnDirectLeagueRoute
  '/statistics/most-common-scores': typeof StatisticsMostCommonScoresRoute
  '/actu/': typeof ActuIndexRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/calendrier/': typeof CalendrierIndexRoute
  '/classement/': typeof ClassementIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/pronostics-football/': typeof PronosticsFootballIndexRoute
  '/resultats-football/': typeof ResultatsFootballIndexRoute
  '/score-hunter/': typeof ScoreHunterIndexRoute
  '/scores-en-direct/': typeof ScoresEnDirectIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/statistics/$league/most-common-scores': typeof StatisticsLeagueMostCommonScoresRoute
  '/statistics/leagues/highest-0-0': typeof StatisticsLeaguesHighest00Route
  '/statistics/leagues/lowest-0-0': typeof StatisticsLeaguesLowest00Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/about'
    | '/actu'
    | '/actualites'
    | '/admin'
    | '/blog'
    | '/bundesliga'
    | '/calculateur-mise'
    | '/calendrier'
    | '/cgu'
    | '/championship'
    | '/changelog'
    | '/chat'
    | '/classement'
    | '/comparer-cotes'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/data-sources'
    | '/editorial-policy'
    | '/forum'
    | '/geo-health'
    | '/go'
    | '/guides'
    | '/jeu-responsable'
    | '/la-liga'
    | '/lab'
    | '/ledger'
    | '/ligue-1'
    | '/ligue-des-champions'
    | '/ligue-europa'
    | '/meilleur-site-pronostic'
    | '/meilleures-cotes'
    | '/mentions-legales'
    | '/methodology'
    | '/opportunities'
    | '/outils'
    | '/pari-du-jour'
    | '/pari-en-direct'
    | '/paris-football'
    | '/politique-publicite'
    | '/portefeuille-mots-cles'
    | '/prediction-history'
    | '/premier-league'
    | '/press'
    | '/pronos-football'
    | '/pronostics-football'
    | '/pronostics-sportifs'
    | '/redaction'
    | '/resultats-football'
    | '/score-data-methodology'
    | '/score-hunter'
    | '/scores-en-direct'
    | '/serie-a'
    | '/sitemap'
    | '/statistics'
    | '/actu/$day'
    | '/actualites/$slug'
    | '/admin/editorial'
    | '/auteurs/betgpt-editorial'
    | '/blog/$slug'
    | '/calendrier/$slug'
    | '/classement/$slug'
    | '/cotes/$matchId'
    | '/equipe/$team'
    | '/forum/$threadId'
    | '/guides/$slug'
    | '/match/$matchId'
    | '/outils/$slug'
    | '/prediction/$predictionId'
    | '/prono/$matchId'
    | '/pronostics-football/$league'
    | '/pronostics-football/aujourdhui'
    | '/pronostics-football/demain'
    | '/rapports/precision'
    | '/resultat/$matchId'
    | '/resultats-football/$league'
    | '/resultats-football/aujourdhui'
    | '/resultats-football/hier'
    | '/score-hunter/$scenario'
    | '/score/$matchId'
    | '/scores-en-direct/$league'
    | '/statistics/most-common-scores'
    | '/actu/'
    | '/actualites/'
    | '/blog/'
    | '/calendrier/'
    | '/classement/'
    | '/forum/'
    | '/guides/'
    | '/outils/'
    | '/pronostics-football/'
    | '/resultats-football/'
    | '/score-hunter/'
    | '/scores-en-direct/'
    | '/statistics/'
    | '/statistics/$league/most-common-scores'
    | '/statistics/leagues/highest-0-0'
    | '/statistics/leagues/lowest-0-0'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/about'
    | '/admin'
    | '/bundesliga'
    | '/calculateur-mise'
    | '/cgu'
    | '/championship'
    | '/changelog'
    | '/chat'
    | '/comparer-cotes'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/data-sources'
    | '/editorial-policy'
    | '/geo-health'
    | '/go'
    | '/jeu-responsable'
    | '/la-liga'
    | '/lab'
    | '/ledger'
    | '/ligue-1'
    | '/ligue-des-champions'
    | '/ligue-europa'
    | '/meilleur-site-pronostic'
    | '/meilleures-cotes'
    | '/mentions-legales'
    | '/methodology'
    | '/opportunities'
    | '/pari-du-jour'
    | '/pari-en-direct'
    | '/paris-football'
    | '/politique-publicite'
    | '/portefeuille-mots-cles'
    | '/prediction-history'
    | '/premier-league'
    | '/press'
    | '/pronos-football'
    | '/pronostics-sportifs'
    | '/redaction'
    | '/score-data-methodology'
    | '/serie-a'
    | '/sitemap'
    | '/actu/$day'
    | '/actualites/$slug'
    | '/admin/editorial'
    | '/auteurs/betgpt-editorial'
    | '/blog/$slug'
    | '/calendrier/$slug'
    | '/classement/$slug'
    | '/cotes/$matchId'
    | '/equipe/$team'
    | '/forum/$threadId'
    | '/guides/$slug'
    | '/match/$matchId'
    | '/outils/$slug'
    | '/prediction/$predictionId'
    | '/prono/$matchId'
    | '/pronostics-football/$league'
    | '/pronostics-football/aujourdhui'
    | '/pronostics-football/demain'
    | '/rapports/precision'
    | '/resultat/$matchId'
    | '/resultats-football/$league'
    | '/resultats-football/aujourdhui'
    | '/resultats-football/hier'
    | '/score-hunter/$scenario'
    | '/score/$matchId'
    | '/scores-en-direct/$league'
    | '/statistics/most-common-scores'
    | '/actu'
    | '/actualites'
    | '/blog'
    | '/calendrier'
    | '/classement'
    | '/forum'
    | '/guides'
    | '/outils'
    | '/pronostics-football'
    | '/resultats-football'
    | '/score-hunter'
    | '/scores-en-direct'
    | '/statistics'
    | '/statistics/$league/most-common-scores'
    | '/statistics/leagues/highest-0-0'
    | '/statistics/leagues/lowest-0-0'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/about'
    | '/actu'
    | '/actualites'
    | '/admin'
    | '/blog'
    | '/bundesliga'
    | '/calculateur-mise'
    | '/calendrier'
    | '/cgu'
    | '/championship'
    | '/changelog'
    | '/chat'
    | '/classement'
    | '/comparer-cotes'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/data-sources'
    | '/editorial-policy'
    | '/forum'
    | '/geo-health'
    | '/go'
    | '/guides'
    | '/jeu-responsable'
    | '/la-liga'
    | '/lab'
    | '/ledger'
    | '/ligue-1'
    | '/ligue-des-champions'
    | '/ligue-europa'
    | '/meilleur-site-pronostic'
    | '/meilleures-cotes'
    | '/mentions-legales'
    | '/methodology'
    | '/opportunities'
    | '/outils'
    | '/pari-du-jour'
    | '/pari-en-direct'
    | '/paris-football'
    | '/politique-publicite'
    | '/portefeuille-mots-cles'
    | '/prediction-history'
    | '/premier-league'
    | '/press'
    | '/pronos-football'
    | '/pronostics-football'
    | '/pronostics-sportifs'
    | '/redaction'
    | '/resultats-football'
    | '/score-data-methodology'
    | '/score-hunter'
    | '/scores-en-direct'
    | '/serie-a'
    | '/sitemap'
    | '/statistics'
    | '/actu/$day'
    | '/actualites/$slug'
    | '/admin_/editorial'
    | '/auteurs_/betgpt-editorial'
    | '/blog/$slug'
    | '/calendrier/$slug'
    | '/classement/$slug'
    | '/cotes/$matchId'
    | '/equipe/$team'
    | '/forum/$threadId'
    | '/guides/$slug'
    | '/match/$matchId'
    | '/outils/$slug'
    | '/prediction/$predictionId'
    | '/prono/$matchId'
    | '/pronostics-football/$league'
    | '/pronostics-football/aujourdhui'
    | '/pronostics-football/demain'
    | '/rapports/precision'
    | '/resultat/$matchId'
    | '/resultats-football/$league'
    | '/resultats-football/aujourdhui'
    | '/resultats-football/hier'
    | '/score-hunter/$scenario'
    | '/score/$matchId'
    | '/scores-en-direct/$league'
    | '/statistics/most-common-scores'
    | '/actu/'
    | '/actualites/'
    | '/blog/'
    | '/calendrier/'
    | '/classement/'
    | '/forum/'
    | '/guides/'
    | '/outils/'
    | '/pronostics-football/'
    | '/resultats-football/'
    | '/score-hunter/'
    | '/scores-en-direct/'
    | '/statistics/'
    | '/statistics/$league/most-common-scores'
    | '/statistics/leagues/highest-0-0'
    | '/statistics/leagues/lowest-0-0'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AboutRoute: typeof AboutRoute
  ActuRoute: typeof ActuRouteWithChildren
  ActualitesRoute: typeof ActualitesRouteWithChildren
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  BundesligaRoute: typeof BundesligaRoute
  CalculateurMiseRoute: typeof CalculateurMiseRoute
  CalendrierRoute: typeof CalendrierRouteWithChildren
  CguRoute: typeof CguRoute
  ChampionshipRoute: typeof ChampionshipRoute
  ChangelogRoute: typeof ChangelogRoute
  ChatRoute: typeof ChatRoute
  ClassementRoute: typeof ClassementRouteWithChildren
  ComparerCotesRoute: typeof ComparerCotesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DataSourcesRoute: typeof DataSourcesRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  ForumRoute: typeof ForumRouteWithChildren
  GeoHealthRoute: typeof GeoHealthRoute
  GoRoute: typeof GoRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  JeuResponsableRoute: typeof JeuResponsableRoute
  LaLigaRoute: typeof LaLigaRoute
  LabRoute: typeof LabRoute
  LedgerRoute: typeof LedgerRoute
  Ligue1Route: typeof Ligue1Route
  LigueDesChampionsRoute: typeof LigueDesChampionsRoute
  LigueEuropaRoute: typeof LigueEuropaRoute
  MeilleurSitePronosticRoute: typeof MeilleurSitePronosticRoute
  MeilleuresCotesRoute: typeof MeilleuresCotesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MethodologyRoute: typeof MethodologyRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OutilsRoute: typeof OutilsRouteWithChildren
  PariDuJourRoute: typeof PariDuJourRoute
  PariEnDirectRoute: typeof PariEnDirectRoute
  ParisFootballRoute: typeof ParisFootballRoute
  PolitiquePubliciteRoute: typeof PolitiquePubliciteRoute
  PortefeuilleMotsClesRoute: typeof PortefeuilleMotsClesRoute
  PredictionHistoryRoute: typeof PredictionHistoryRoute
  PremierLeagueRoute: typeof PremierLeagueRoute
  PressRoute: typeof PressRoute
  PronosFootballRoute: typeof PronosFootballRoute
  PronosticsFootballRoute: typeof PronosticsFootballRouteWithChildren
  PronosticsSportifsRoute: typeof PronosticsSportifsRoute
  RedactionRoute: typeof RedactionRoute
  ResultatsFootballRoute: typeof ResultatsFootballRouteWithChildren
  ScoreDataMethodologyRoute: typeof ScoreDataMethodologyRoute
  ScoreHunterRoute: typeof ScoreHunterRouteWithChildren
  ScoresEnDirectRoute: typeof ScoresEnDirectRouteWithChildren
  SerieARoute: typeof SerieARoute
  SitemapRoute: typeof SitemapRoute
  StatisticsRoute: typeof StatisticsRouteWithChildren
  AdminEditorialRoute: typeof AdminEditorialRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AuteursBetgptEditorialRoute: typeof AuteursBetgptEditorialRoute
  CotesMatchIdRoute: typeof CotesMatchIdRoute
  EquipeTeamRoute: typeof EquipeTeamRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  PredictionPredictionIdRoute: typeof PredictionPredictionIdRoute
  PronoMatchIdRoute: typeof PronoMatchIdRoute
  RapportsPrecisionRoute: typeof RapportsPrecisionRoute
  ResultatMatchIdRoute: typeof ResultatMatchIdRoute
  ScoreMatchIdRoute: typeof ScoreMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actu': {
      id: '/actu'
      path: '/actu'
      fullPath: '/actu'
      preLoaderRoute: typeof ActuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundesliga': {
      id: '/bundesliga'
      path: '/bundesliga'
      fullPath: '/bundesliga'
      preLoaderRoute: typeof BundesligaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateur-mise': {
      id: '/calculateur-mise'
      path: '/calculateur-mise'
      fullPath: '/calculateur-mise'
      preLoaderRoute: typeof CalculateurMiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/championship': {
      id: '/championship'
      path: '/championship'
      fullPath: '/championship'
      preLoaderRoute: typeof ChampionshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer-cotes': {
      id: '/comparer-cotes'
      path: '/comparer-cotes'
      fullPath: '/comparer-cotes'
      preLoaderRoute: typeof ComparerCotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo-health': {
      id: '/geo-health'
      path: '/geo-health'
      fullPath: '/geo-health'
      preLoaderRoute: typeof GeoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeu-responsable': {
      id: '/jeu-responsable'
      path: '/jeu-responsable'
      fullPath: '/jeu-responsable'
      preLoaderRoute: typeof JeuResponsableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-liga': {
      id: '/la-liga'
      path: '/la-liga'
      fullPath: '/la-liga'
      preLoaderRoute: typeof LaLigaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligue-1': {
      id: '/ligue-1'
      path: '/ligue-1'
      fullPath: '/ligue-1'
      preLoaderRoute: typeof Ligue1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligue-des-champions': {
      id: '/ligue-des-champions'
      path: '/ligue-des-champions'
      fullPath: '/ligue-des-champions'
      preLoaderRoute: typeof LigueDesChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligue-europa': {
      id: '/ligue-europa'
      path: '/ligue-europa'
      fullPath: '/ligue-europa'
      preLoaderRoute: typeof LigueEuropaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meilleur-site-pronostic': {
      id: '/meilleur-site-pronostic'
      path: '/meilleur-site-pronostic'
      fullPath: '/meilleur-site-pronostic'
      preLoaderRoute: typeof MeilleurSitePronosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meilleures-cotes': {
      id: '/meilleures-cotes'
      path: '/meilleures-cotes'
      fullPath: '/meilleures-cotes'
      preLoaderRoute: typeof MeilleuresCotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pari-du-jour': {
      id: '/pari-du-jour'
      path: '/pari-du-jour'
      fullPath: '/pari-du-jour'
      preLoaderRoute: typeof PariDuJourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pari-en-direct': {
      id: '/pari-en-direct'
      path: '/pari-en-direct'
      fullPath: '/pari-en-direct'
      preLoaderRoute: typeof PariEnDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paris-football': {
      id: '/paris-football'
      path: '/paris-football'
      fullPath: '/paris-football'
      preLoaderRoute: typeof ParisFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-publicite': {
      id: '/politique-publicite'
      path: '/politique-publicite'
      fullPath: '/politique-publicite'
      preLoaderRoute: typeof PolitiquePubliciteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefeuille-mots-cles': {
      id: '/portefeuille-mots-cles'
      path: '/portefeuille-mots-cles'
      fullPath: '/portefeuille-mots-cles'
      preLoaderRoute: typeof PortefeuilleMotsClesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction-history': {
      id: '/prediction-history'
      path: '/prediction-history'
      fullPath: '/prediction-history'
      preLoaderRoute: typeof PredictionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premier-league': {
      id: '/premier-league'
      path: '/premier-league'
      fullPath: '/premier-league'
      preLoaderRoute: typeof PremierLeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronos-football': {
      id: '/pronos-football'
      path: '/pronos-football'
      fullPath: '/pronos-football'
      preLoaderRoute: typeof PronosFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronostics-football': {
      id: '/pronostics-football'
      path: '/pronostics-football'
      fullPath: '/pronostics-football'
      preLoaderRoute: typeof PronosticsFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronostics-sportifs': {
      id: '/pronostics-sportifs'
      path: '/pronostics-sportifs'
      fullPath: '/pronostics-sportifs'
      preLoaderRoute: typeof PronosticsSportifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaction': {
      id: '/redaction'
      path: '/redaction'
      fullPath: '/redaction'
      preLoaderRoute: typeof RedactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats-football': {
      id: '/resultats-football'
      path: '/resultats-football'
      fullPath: '/resultats-football'
      preLoaderRoute: typeof ResultatsFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-data-methodology': {
      id: '/score-data-methodology'
      path: '/score-data-methodology'
      fullPath: '/score-data-methodology'
      preLoaderRoute: typeof ScoreDataMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-hunter': {
      id: '/score-hunter'
      path: '/score-hunter'
      fullPath: '/score-hunter'
      preLoaderRoute: typeof ScoreHunterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores-en-direct': {
      id: '/scores-en-direct'
      path: '/scores-en-direct'
      fullPath: '/scores-en-direct'
      preLoaderRoute: typeof ScoresEnDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie-a': {
      id: '/serie-a'
      path: '/serie-a'
      fullPath: '/serie-a'
      preLoaderRoute: typeof SerieARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actu/': {
      id: '/actu/'
      path: '/'
      fullPath: '/actu/'
      preLoaderRoute: typeof ActuIndexRouteImport
      parentRoute: typeof ActuRoute
    }
    '/actu/$day': {
      id: '/actu/$day'
      path: '/$day'
      fullPath: '/actu/$day'
      preLoaderRoute: typeof ActuDayRouteImport
      parentRoute: typeof ActuRoute
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/admin_/editorial': {
      id: '/admin_/editorial'
      path: '/admin/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AdminEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/social': {
      id: '/admin_/social'
      path: '/admin/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auteurs_/betgpt-editorial': {
      id: '/auteurs_/betgpt-editorial'
      path: '/auteurs/betgpt-editorial'
      fullPath: '/auteurs/betgpt-editorial'
      preLoaderRoute: typeof AuteursBetgptEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/calendrier/': {
      id: '/calendrier/'
      path: '/'
      fullPath: '/calendrier/'
      preLoaderRoute: typeof CalendrierIndexRouteImport
      parentRoute: typeof CalendrierRoute
    }
    '/calendrier/$slug': {
      id: '/calendrier/$slug'
      path: '/$slug'
      fullPath: '/calendrier/$slug'
      preLoaderRoute: typeof CalendrierSlugRouteImport
      parentRoute: typeof CalendrierRoute
    }
    '/classement/': {
      id: '/classement/'
      path: '/'
      fullPath: '/classement/'
      preLoaderRoute: typeof ClassementIndexRouteImport
      parentRoute: typeof ClassementRoute
    }
    '/classement/$slug': {
      id: '/classement/$slug'
      path: '/$slug'
      fullPath: '/classement/$slug'
      preLoaderRoute: typeof ClassementSlugRouteImport
      parentRoute: typeof ClassementRoute
    }
    '/cotes/$matchId': {
      id: '/cotes/$matchId'
      path: '/cotes/$matchId'
      fullPath: '/cotes/$matchId'
      preLoaderRoute: typeof CotesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$team': {
      id: '/equipe/$team'
      path: '/equipe/$team'
      fullPath: '/equipe/$team'
      preLoaderRoute: typeof EquipeTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/$threadId': {
      id: '/forum/$threadId'
      path: '/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof ForumThreadIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/': {
      id: '/outils/'
      path: '/'
      fullPath: '/outils/'
      preLoaderRoute: typeof OutilsIndexRouteImport
      parentRoute: typeof OutilsRoute
    }
    '/outils/$slug': {
      id: '/outils/$slug'
      path: '/$slug'
      fullPath: '/outils/$slug'
      preLoaderRoute: typeof OutilsSlugRouteImport
      parentRoute: typeof OutilsRoute
    }
    '/prediction/$predictionId': {
      id: '/prediction/$predictionId'
      path: '/prediction/$predictionId'
      fullPath: '/prediction/$predictionId'
      preLoaderRoute: typeof PredictionPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prono/$matchId': {
      id: '/prono/$matchId'
      path: '/prono/$matchId'
      fullPath: '/prono/$matchId'
      preLoaderRoute: typeof PronoMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronostics-football/': {
      id: '/pronostics-football/'
      path: '/'
      fullPath: '/pronostics-football/'
      preLoaderRoute: typeof PronosticsFootballIndexRouteImport
      parentRoute: typeof PronosticsFootballRoute
    }
    '/pronostics-football/$league': {
      id: '/pronostics-football/$league'
      path: '/$league'
      fullPath: '/pronostics-football/$league'
      preLoaderRoute: typeof PronosticsFootballLeagueRouteImport
      parentRoute: typeof PronosticsFootballRoute
    }
    '/pronostics-football/aujourdhui': {
      id: '/pronostics-football/aujourdhui'
      path: '/aujourdhui'
      fullPath: '/pronostics-football/aujourdhui'
      preLoaderRoute: typeof PronosticsFootballAujourdhuiRouteImport
      parentRoute: typeof PronosticsFootballRoute
    }
    '/pronostics-football/demain': {
      id: '/pronostics-football/demain'
      path: '/demain'
      fullPath: '/pronostics-football/demain'
      preLoaderRoute: typeof PronosticsFootballDemainRouteImport
      parentRoute: typeof PronosticsFootballRoute
    }
    '/rapports/precision': {
      id: '/rapports/precision'
      path: '/rapports/precision'
      fullPath: '/rapports/precision'
      preLoaderRoute: typeof RapportsPrecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultat/$matchId': {
      id: '/resultat/$matchId'
      path: '/resultat/$matchId'
      fullPath: '/resultat/$matchId'
      preLoaderRoute: typeof ResultatMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats-football/': {
      id: '/resultats-football/'
      path: '/'
      fullPath: '/resultats-football/'
      preLoaderRoute: typeof ResultatsFootballIndexRouteImport
      parentRoute: typeof ResultatsFootballRoute
    }
    '/resultats-football/$league': {
      id: '/resultats-football/$league'
      path: '/$league'
      fullPath: '/resultats-football/$league'
      preLoaderRoute: typeof ResultatsFootballLeagueRouteImport
      parentRoute: typeof ResultatsFootballRoute
    }
    '/resultats-football/aujourdhui': {
      id: '/resultats-football/aujourdhui'
      path: '/aujourdhui'
      fullPath: '/resultats-football/aujourdhui'
      preLoaderRoute: typeof ResultatsFootballAujourdhuiRouteImport
      parentRoute: typeof ResultatsFootballRoute
    }
    '/resultats-football/hier': {
      id: '/resultats-football/hier'
      path: '/hier'
      fullPath: '/resultats-football/hier'
      preLoaderRoute: typeof ResultatsFootballHierRouteImport
      parentRoute: typeof ResultatsFootballRoute
    }
    '/score-hunter/': {
      id: '/score-hunter/'
      path: '/'
      fullPath: '/score-hunter/'
      preLoaderRoute: typeof ScoreHunterIndexRouteImport
      parentRoute: typeof ScoreHunterRoute
    }
    '/score-hunter/$scenario': {
      id: '/score-hunter/$scenario'
      path: '/$scenario'
      fullPath: '/score-hunter/$scenario'
      preLoaderRoute: typeof ScoreHunterScenarioRouteImport
      parentRoute: typeof ScoreHunterRoute
    }
    '/score/$matchId': {
      id: '/score/$matchId'
      path: '/score/$matchId'
      fullPath: '/score/$matchId'
      preLoaderRoute: typeof ScoreMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores-en-direct/': {
      id: '/scores-en-direct/'
      path: '/'
      fullPath: '/scores-en-direct/'
      preLoaderRoute: typeof ScoresEnDirectIndexRouteImport
      parentRoute: typeof ScoresEnDirectRoute
    }
    '/scores-en-direct/$league': {
      id: '/scores-en-direct/$league'
      path: '/$league'
      fullPath: '/scores-en-direct/$league'
      preLoaderRoute: typeof ScoresEnDirectLeagueRouteImport
      parentRoute: typeof ScoresEnDirectRoute
    }
    '/statistics/': {
      id: '/statistics/'
      path: '/'
      fullPath: '/statistics/'
      preLoaderRoute: typeof StatisticsIndexRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/most-common-scores': {
      id: '/statistics/most-common-scores'
      path: '/most-common-scores'
      fullPath: '/statistics/most-common-scores'
      preLoaderRoute: typeof StatisticsMostCommonScoresRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/$league/most-common-scores': {
      id: '/statistics/$league/most-common-scores'
      path: '/$league/most-common-scores'
      fullPath: '/statistics/$league/most-common-scores'
      preLoaderRoute: typeof StatisticsLeagueMostCommonScoresRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/leagues/highest-0-0': {
      id: '/statistics/leagues/highest-0-0'
      path: '/leagues/highest-0-0'
      fullPath: '/statistics/leagues/highest-0-0'
      preLoaderRoute: typeof StatisticsLeaguesHighest00RouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/leagues/lowest-0-0': {
      id: '/statistics/leagues/lowest-0-0'
      path: '/leagues/lowest-0-0'
      fullPath: '/statistics/leagues/lowest-0-0'
      preLoaderRoute: typeof StatisticsLeaguesLowest00RouteImport
      parentRoute: typeof StatisticsRoute
    }
  }
}

interface ActuRouteChildren {
  ActuDayRoute: typeof ActuDayRoute
  ActuIndexRoute: typeof ActuIndexRoute
}

const ActuRouteChildren: ActuRouteChildren = {
  ActuDayRoute: ActuDayRoute,
  ActuIndexRoute: ActuIndexRoute,
}

const ActuRouteWithChildren = ActuRoute._addFileChildren(ActuRouteChildren)

interface ActualitesRouteChildren {
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
}

const ActualitesRouteChildren: ActualitesRouteChildren = {
  ActualitesSlugRoute: ActualitesSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
}

const ActualitesRouteWithChildren = ActualitesRoute._addFileChildren(
  ActualitesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CalendrierRouteChildren {
  CalendrierSlugRoute: typeof CalendrierSlugRoute
  CalendrierIndexRoute: typeof CalendrierIndexRoute
}

const CalendrierRouteChildren: CalendrierRouteChildren = {
  CalendrierSlugRoute: CalendrierSlugRoute,
  CalendrierIndexRoute: CalendrierIndexRoute,
}

const CalendrierRouteWithChildren = CalendrierRoute._addFileChildren(
  CalendrierRouteChildren,
)

interface ClassementRouteChildren {
  ClassementSlugRoute: typeof ClassementSlugRoute
  ClassementIndexRoute: typeof ClassementIndexRoute
}

const ClassementRouteChildren: ClassementRouteChildren = {
  ClassementSlugRoute: ClassementSlugRoute,
  ClassementIndexRoute: ClassementIndexRoute,
}

const ClassementRouteWithChildren = ClassementRoute._addFileChildren(
  ClassementRouteChildren,
)

interface ForumRouteChildren {
  ForumThreadIdRoute: typeof ForumThreadIdRoute
  ForumIndexRoute: typeof ForumIndexRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumThreadIdRoute: ForumThreadIdRoute,
  ForumIndexRoute: ForumIndexRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface OutilsRouteChildren {
  OutilsSlugRoute: typeof OutilsSlugRoute
  OutilsIndexRoute: typeof OutilsIndexRoute
}

const OutilsRouteChildren: OutilsRouteChildren = {
  OutilsSlugRoute: OutilsSlugRoute,
  OutilsIndexRoute: OutilsIndexRoute,
}

const OutilsRouteWithChildren =
  OutilsRoute._addFileChildren(OutilsRouteChildren)

interface PronosticsFootballRouteChildren {
  PronosticsFootballLeagueRoute: typeof PronosticsFootballLeagueRoute
  PronosticsFootballAujourdhuiRoute: typeof PronosticsFootballAujourdhuiRoute
  PronosticsFootballDemainRoute: typeof PronosticsFootballDemainRoute
  PronosticsFootballIndexRoute: typeof PronosticsFootballIndexRoute
}

const PronosticsFootballRouteChildren: PronosticsFootballRouteChildren = {
  PronosticsFootballLeagueRoute: PronosticsFootballLeagueRoute,
  PronosticsFootballAujourdhuiRoute: PronosticsFootballAujourdhuiRoute,
  PronosticsFootballDemainRoute: PronosticsFootballDemainRoute,
  PronosticsFootballIndexRoute: PronosticsFootballIndexRoute,
}

const PronosticsFootballRouteWithChildren =
  PronosticsFootballRoute._addFileChildren(PronosticsFootballRouteChildren)

interface ResultatsFootballRouteChildren {
  ResultatsFootballLeagueRoute: typeof ResultatsFootballLeagueRoute
  ResultatsFootballAujourdhuiRoute: typeof ResultatsFootballAujourdhuiRoute
  ResultatsFootballHierRoute: typeof ResultatsFootballHierRoute
  ResultatsFootballIndexRoute: typeof ResultatsFootballIndexRoute
}

const ResultatsFootballRouteChildren: ResultatsFootballRouteChildren = {
  ResultatsFootballLeagueRoute: ResultatsFootballLeagueRoute,
  ResultatsFootballAujourdhuiRoute: ResultatsFootballAujourdhuiRoute,
  ResultatsFootballHierRoute: ResultatsFootballHierRoute,
  ResultatsFootballIndexRoute: ResultatsFootballIndexRoute,
}

const ResultatsFootballRouteWithChildren =
  ResultatsFootballRoute._addFileChildren(ResultatsFootballRouteChildren)

interface ScoreHunterRouteChildren {
  ScoreHunterScenarioRoute: typeof ScoreHunterScenarioRoute
  ScoreHunterIndexRoute: typeof ScoreHunterIndexRoute
}

const ScoreHunterRouteChildren: ScoreHunterRouteChildren = {
  ScoreHunterScenarioRoute: ScoreHunterScenarioRoute,
  ScoreHunterIndexRoute: ScoreHunterIndexRoute,
}

const ScoreHunterRouteWithChildren = ScoreHunterRoute._addFileChildren(
  ScoreHunterRouteChildren,
)

interface ScoresEnDirectRouteChildren {
  ScoresEnDirectLeagueRoute: typeof ScoresEnDirectLeagueRoute
  ScoresEnDirectIndexRoute: typeof ScoresEnDirectIndexRoute
}

const ScoresEnDirectRouteChildren: ScoresEnDirectRouteChildren = {
  ScoresEnDirectLeagueRoute: ScoresEnDirectLeagueRoute,
  ScoresEnDirectIndexRoute: ScoresEnDirectIndexRoute,
}

const ScoresEnDirectRouteWithChildren = ScoresEnDirectRoute._addFileChildren(
  ScoresEnDirectRouteChildren,
)

interface StatisticsRouteChildren {
  StatisticsMostCommonScoresRoute: typeof StatisticsMostCommonScoresRoute
  StatisticsIndexRoute: typeof StatisticsIndexRoute
  StatisticsLeagueMostCommonScoresRoute: typeof StatisticsLeagueMostCommonScoresRoute
  StatisticsLeaguesHighest00Route: typeof StatisticsLeaguesHighest00Route
  StatisticsLeaguesLowest00Route: typeof StatisticsLeaguesLowest00Route
}

const StatisticsRouteChildren: StatisticsRouteChildren = {
  StatisticsMostCommonScoresRoute: StatisticsMostCommonScoresRoute,
  StatisticsIndexRoute: StatisticsIndexRoute,
  StatisticsLeagueMostCommonScoresRoute: StatisticsLeagueMostCommonScoresRoute,
  StatisticsLeaguesHighest00Route: StatisticsLeaguesHighest00Route,
  StatisticsLeaguesLowest00Route: StatisticsLeaguesLowest00Route,
}

const StatisticsRouteWithChildren = StatisticsRoute._addFileChildren(
  StatisticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AboutRoute: AboutRoute,
  ActuRoute: ActuRouteWithChildren,
  ActualitesRoute: ActualitesRouteWithChildren,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  BundesligaRoute: BundesligaRoute,
  CalculateurMiseRoute: CalculateurMiseRoute,
  CalendrierRoute: CalendrierRouteWithChildren,
  CguRoute: CguRoute,
  ChampionshipRoute: ChampionshipRoute,
  ChangelogRoute: ChangelogRoute,
  ChatRoute: ChatRoute,
  ClassementRoute: ClassementRouteWithChildren,
  ComparerCotesRoute: ComparerCotesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DataSourcesRoute: DataSourcesRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  ForumRoute: ForumRouteWithChildren,
  GeoHealthRoute: GeoHealthRoute,
  GoRoute: GoRoute,
  GuidesRoute: GuidesRouteWithChildren,
  JeuResponsableRoute: JeuResponsableRoute,
  LaLigaRoute: LaLigaRoute,
  LabRoute: LabRoute,
  LedgerRoute: LedgerRoute,
  Ligue1Route: Ligue1Route,
  LigueDesChampionsRoute: LigueDesChampionsRoute,
  LigueEuropaRoute: LigueEuropaRoute,
  MeilleurSitePronosticRoute: MeilleurSitePronosticRoute,
  MeilleuresCotesRoute: MeilleuresCotesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MethodologyRoute: MethodologyRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OutilsRoute: OutilsRouteWithChildren,
  PariDuJourRoute: PariDuJourRoute,
  PariEnDirectRoute: PariEnDirectRoute,
  ParisFootballRoute: ParisFootballRoute,
  PolitiquePubliciteRoute: PolitiquePubliciteRoute,
  PortefeuilleMotsClesRoute: PortefeuilleMotsClesRoute,
  PredictionHistoryRoute: PredictionHistoryRoute,
  PremierLeagueRoute: PremierLeagueRoute,
  PressRoute: PressRoute,
  PronosFootballRoute: PronosFootballRoute,
  PronosticsFootballRoute: PronosticsFootballRouteWithChildren,
  PronosticsSportifsRoute: PronosticsSportifsRoute,
  RedactionRoute: RedactionRoute,
  ResultatsFootballRoute: ResultatsFootballRouteWithChildren,
  ScoreDataMethodologyRoute: ScoreDataMethodologyRoute,
  ScoreHunterRoute: ScoreHunterRouteWithChildren,
  ScoresEnDirectRoute: ScoresEnDirectRouteWithChildren,
  SerieARoute: SerieARoute,
  SitemapRoute: SitemapRoute,
  StatisticsRoute: StatisticsRouteWithChildren,
  AdminEditorialRoute: AdminEditorialRoute,
  AdminSocialRoute: AdminSocialRoute,
  AuteursBetgptEditorialRoute: AuteursBetgptEditorialRoute,
  CotesMatchIdRoute: CotesMatchIdRoute,
  EquipeTeamRoute: EquipeTeamRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  PredictionPredictionIdRoute: PredictionPredictionIdRoute,
  PronoMatchIdRoute: PronoMatchIdRoute,
  RapportsPrecisionRoute: RapportsPrecisionRoute,
  ResultatMatchIdRoute: ResultatMatchIdRoute,
  ScoreMatchIdRoute: ScoreMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
